services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatwoot_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  rails:
    build:
      context: .
      dockerfile: Dockerfile.simple
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_URL: redis://redis:6379
      RAILS_ENV: development
      NODE_ENV: development
    volumes:
      - .:/app
      - gem_cache:/gems

volumes:
  postgres_data:
  redis_data:
  gem_cache:
