version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - RAILS_ENV=production
    environment:
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true
      - MALLOC_ARENA_MAX=2
      - WEB_CONCURRENCY=2
      - RAILS_MAX_THREADS=5
      - DATABASE_URL=postgres://postgres@db:5432/unichat_production
      - REDIS_URL=redis://redis:6379/1
    ports:
      - "3000:3000"
    volumes:
      - tmp:/app/tmp
      - bundle:/usr/local/bundle
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=unichat_production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  tmp:
  bundle:
