version: '3.8'

services:
  web:
    build:
      context: https://github.com/CecilGarapoJr/unichat.git#main
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true
      - MALLOC_ARENA_MAX=2
      - WEB_CONCURRENCY=2
      - RAILS_MAX_THREADS=5
    ports:
      - "3000:3000"
    volumes:
      - tmp:/app/tmp
      - public:/app/public
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_DB=${DB_NAME:-unichat_production}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  tmp:
  public:
  bundle:
  node_modules:
