version: '3.8'
services:
  web:
    image: twunhuman/unichat:latest
    environment:
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true
      - MALLOC_ARENA_MAX=2
      - WEB_CONCURRENCY=2
      - RAILS_MAX_THREADS=5
      - DATABASE_URL=postgres://postgres:postgres@db:5432/unichat_production
      - REDIS_URL=redis://redis:6379/1
      - SECRET_KEY_BASE_FILE=/run/secrets/secret_key_base
    ports:
      - "3000:3000"
    secrets:
      - secret_key_base
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_DB=unichat_production
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

secrets:
  secret_key_base:
    file: ./config/secrets/secret_key_base.txt
