[phases.setup]
nixPkgs = ["nodejs_20", "ruby_3_1"]
nixLibs = ["libuuid", "libGL"]
nixOverlays = ["https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz"]
aptPkgs = [
    "libpq-dev",
    "libvips",
    "postgresql",
    "libmagickwand-dev",
    "imagemagick",
    "build-essential",
    "libssl-dev",
    "zlib1g-dev"
]
cmds = [
    "npm install -g corepack@0.24.1",
    "corepack enable",
    "corepack prepare pnpm@9 --activate",
    "gem install bundler:2.4.22"
]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "bundle config set --local path 'vendor/bundle'",
    "bundle config set --local deployment 'true'",
    "bundle install --jobs=4",
    "pnpm install --frozen-lockfile --prefer-offline"
]
cacheDirectories = [
    "/root/.local/share/pnpm/store/v3",
    "node_modules/.cache",
    ".vite",
    "vendor/bundle",
    "tmp/cache"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "bundle exec rake assets:clean",
    "bundle exec rake assets:precompile",
    "pnpm run build:sdk",
    "pnpm run build"
]

[phases.release]
dependsOn = ["build"]
cmds = [
    "bundle exec rake db:migrate",
    "bundle exec rake db:seed"
]

[start]
cmd = "bundle exec puma -C config/puma.rb"

[variables]
NODE_ENV = "production"
RAILS_ENV = "production"
VITE_CJS_IGNORE_WARNING = "true"
VITE_BUILD_WATCH = "false"
BUNDLE_PATH = "vendor/bundle"
GEM_PATH = "/usr/local/bundle"
RAILS_LOG_TO_STDOUT = "true"
RAILS_SERVE_STATIC_FILES = "true"
BUNDLE_WITHOUT = "development:test"

[nixpkgs]
archive = "5148520bfab61f99fd25fb9ff7bfbb50dad3c9db"

[build]
builder = "nixpacks"
