[phases.setup]
nixPkgs = [
  "nodejs_20"
]
cmds = [
  "npm install -g pnpm@9"
]

[phases.install]
cmds = [
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "pnpm run build"
]
