[phases.setup]
nixPkgs = ["nodejs_20", "ruby_3_1"]
nixLibs = ["libuuid", "libGL"]
aptPkgs = [
    "libpq-dev",
    "libvips",
    "postgresql",
    "libmagickwand-dev",
    "imagemagick",
    "build-essential",
    "libssl-dev",
    "zlib1g-dev",
    "ca-certificates"
]
cmds = [
    "mkdir -p /app/tmp/pids /app/tmp/cache",
    "npm install -g corepack@0.24.1",
    "corepack enable",
    "corepack prepare pnpm@9.6.1 --activate",
    "gem update --system",
    "gem install bundler -v 2.4.22"
]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "bundle config set --local deployment 'true'",
    "bundle config set --local without 'development test'",
    "bundle config set --local path 'vendor/bundle'",
    "bundle config set build.nokogiri --use-system-libraries",
    "bundle install --jobs=4 --retry=3 --clean",
    "pnpm install --frozen-lockfile --prefer-offline"
]
cacheDirectories = [
    "/root/.local/share/pnpm/store/v3",
    "node_modules/.cache",
    ".vite",
    "vendor/bundle",
    "tmp/cache",
    "public/assets"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "RAILS_ENV=production NODE_ENV=production bundle exec rake assets:clobber || true",
    "RAILS_ENV=production NODE_ENV=production SECRET_KEY_BASE=dummy bundle exec rake assets:precompile || true",
    "RAILS_ENV=production NODE_ENV=production pnpm run build:sdk || true",
    "RAILS_ENV=production NODE_ENV=production pnpm run build"
]

[phases.release]
dependsOn = ["build"]
cmds = [
    "bundle exec rake db:migrate",
    "bundle exec rake db:seed"
]

[start]
cmd = "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"

[variables]
NODE_ENV = "production"
RAILS_ENV = "production"
VITE_CJS_IGNORE_WARNING = "true"
VITE_BUILD_WATCH = "false"
BUNDLE_PATH = "vendor/bundle"
GEM_PATH = "/usr/local/bundle"
RAILS_LOG_TO_STDOUT = "true"
RAILS_SERVE_STATIC_FILES = "true"
BUNDLE_WITHOUT = "development:test"
BUNDLE_DEPLOYMENT = "true"
BUNDLE_JOBS = "4"
RAILS_MAX_THREADS = "5"
WEB_CONCURRENCY = "2"
PORT = "3000"
MALLOC_ARENA_MAX = "2"

[nixpkgs]
archive = "5148520bfab61f99fd25fb9ff7bfbb50dad3c9db"

[build]
builder = "nixpacks"
