entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "unichat@digitalgrowth.global"
      storage: "/etc/traefik/acme.json"
      httpChallenge:
        entryPoint: web
